
services:
 booksyapp:
  
  image: mercy/booksyapp:1.0.0
  build: .
  ports:
   - "8890:8000"
  env_file: 
   - .env
  depends_on:
   - db 
  volumes:
      - ./:/var/www/html

 db:
  image: postgres:12
  ports:
   - "5544:5432"
  environment:
   POSTGRES_USER: shiftechafrica
   POSTGRES_PASSWORD: 12345678
   POSTGRES_DB: booksy_crud
  volumes: 
   - pgdata:/var/lib/postgresql/data
  
volumes:
 pgdata: {} 